### ISSUE TITLE
Fehler: Admin - Fahrer hinzufügen

### ISSUE THREAD

**Issue by vanfer** [xenco/fahrrad#17]
Wird ein neuer Fahrer erstellt und wieder gelöscht, kann man keinen Fahrer mit gleichem Namen erstellen, es sei denn man läd den Browser neu. Funktioniert auch nicht bei zusätzlicher Angabe von Gewicht/Größe/Email. Änderung des Namen dagegen erstellt neuen Fahrer

**Comment by xenco** [comment]
Liegt an der Art und Weise wie das Inline Editing in der Tabelle verarbeitet wird.
Behebung ist zu umfangreich. Vorschlag: An dieser Stelle eine neue Form als Overlay benutzen.
