### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by Clamater** [xenco/fahrrad#23]
Wenn man auf der Login-Seite für den Admin ist und dann in das eingabefeld klickt erscheint
"Passwort verwenden für: (Kein Nutzername)" 
ist irgendwie verwirrend und unnötig

**Comment by xenco** [comment]
Das ist das Browser Feature zum speichern von Formulardaten. Kann sein, dass es ausgelöst wird, weil das Feld "passwort" heißt.
Wird behoben, hat aber eine niedrige Priorität.

**Comment by xenco** [comment]
Fehler behoben.
