### ISSUE TITLE
Validierung Formular "Fahrer hinzufügen"

### ISSUE THREAD

**Issue by Clamater** [xenco/fahrrad#39]
wenn im Formular falsche Daten eingegeben werden, kann man nicht auf den Button "hinzufügen" klicken, aber es wird auch nicht angezeigt wieso. Trotzdem wird der Fahrer jedoch hinzufügt.
Ergo wenn man 10x den Button "hinzufügen" ausprobiert, dann wird der Fahrer auch 10x hinzugefügt

**Comment by vanfer** [comment]
nicht reproduzierbar

**Comment by xenco** [comment]
Sollte auch mit Bug #37 behoben worden sein
