### ISSUE TITLE
Fahrer zuordnen

### ISSUE THREAD

**Issue by Clamater** [xenco/fahrrad#55]
Wenn ein Fahrer bereits zugeordnet ist, und dann wird er einem anderen Fahrrad zugeordnet, dann erscheint der Dialog nicht mehr und die vorherige Zuordnung wird gelöscht

**Comment by xenco** [comment]
Dialog erscheint wie gewohnt, musst eventuell den Reload der Seite abwarten. Kann ich so nicht reproduzieren.
